"""empty message

Revision ID: c70c9409b858
Revises: e97ce4c44fca
Create Date: 2022-04-24 11:32:03.899296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70c9409b858'
down_revision = 'e97ce4c44fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_new_name_key', 'users', type_='unique')
    op.drop_column('users', 'new_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_new_name_key', 'users', ['new_name'])
    # ### end Alembic commands ###
