"""empty message

Revision ID: e97ce4c44fca
Revises: 
Create Date: 2022-04-24 11:31:38.098974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97ce4c44fca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_name', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['new_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'new_name')
    # ### end Alembic commands ###
